from enum import Enum


class TaskType(str, Enum):
    """
    Task types which are supported by OLI2D.
    """

    # OBJECT_DETECTION = "OBJECT_DETECTION"
    # CLASSIFICATION = "CLASSIFICATION"
    # SEGMENTATION = "SEGMENTATION"
    # HAND_LANDMARK_RECOGNITION = "HAND_LANDMARK_RECOGNITION"
    # GESTURE_RECOGNITION = "GESTURE_RECOGNITION"
    EMBEDDING = "EMBEDDING"
    # FACE_RECOGNITION = "FACE_RECOGNITION"
    # FACE_LANDMARK_RECOGNITION = "FACE_LANDMARK_RECOGNITION"
    # POSE_LANDMARK_RECOGNITION = "POSE_LANDMARK_RECOGNITION"
